version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/java-hello
hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
