version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/docker-app

hooks:
  AfterInstall:
    - location: scripts/stop_container.sh
      timeout: 10
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 20
