version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mkdir -p output
      - javac WebServer.java -d output
artifacts:
  files:
    - output/**
    - appspec.yml
    - scripts/**
